// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Action struct {
	ID        int32
	Amount    float64
	UserID    int32
	CreatedAt time.Time
}

type Batch struct {
	ID         int32
	Dispatched bool
	Amount     float64
	UserID     int32
	CreatedAt  time.Time
}

type Transaction struct {
	ID        int32
	Amount    float64
	UserID    int32
	CreatedAt time.Time
}

type User struct {
	ID        int32
	Name      string
	CreatedAt time.Time
}
